// libs/swootreact/src/lib/components/button/button.tsx
import * as React from 'react';
import { ButtonKind, ButtonSize, ThemeColor } from '@swoot/types';

interface Props<T extends React.ElementType> {
  as?: T;
  color?: ThemeColor;
  kind?: ButtonKind;
  size?: ButtonSize;
  children?: React.ReactNode;
}

type ButtonProps<T extends React.ElementType> = Props<T> &
  Omit<React.ComponentPropsWithoutRef<T>, keyof Props<T>>;

export function Button<T extends React.ElementType = 'button'>({
  as,
  color = 'primary',
  kind = 'fill',
  size = 'md',
  ...props
}: ButtonProps<T>) {
  const Component = as || 'button';

  const classes = `
    swoot-button
    swoot-button--${color}
    swoot-button--${kind}
    swoot-button--${size}
  `;

  return <Component {...props} className={classes} />;
}

// libs/swootng/src/lib/components/button.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { ButtonKind, ButtonSize, ThemeColor } from '@swoot/types';

@Component({
  selector: '[swoot-button]',
  templateUrl: 'button.component.html',
})
export class ButtonComponent {
  @Input() color: ThemeColor = 'primary';
  @Input() kind: ButtonKind = 'fill';
  @Input() size: ButtonSize = 'md';

  @HostBinding('class')
  get classes() {
    return `
      swoot-button
      swoot-button--${this.color}
      swoot-button--${this.kind}
      swoot-button--${this.size}
    `;
  }
}
